### ISSUE TITLE
Not working properly with @staticmethod

### ISSUE THREAD

**Issue by teodor-t-tenev** [hostar/python-inlay-putter#1]
inlay hint is not shown for static methods.

**Comment by hostar** [comment]
Thanks for the report. Can you let me know if the problem is fixed with this new version: https://github.com/hostar/python-inlay-putter/releases/tag/0.0.4 ?

**Comment by teodor-t-tenev** [comment]
Works perfect with static methods now. Thanks for the fast reaction :)
