### ISSUE TITLE
Error on pycharm pro 213

### ISSUE THREAD

**Issue by Danjar27** [hostar/python-inlay-putter#6]
I got this error when I tried to install it. Any idea?

![image](https://user-images.githubusercontent.com/76726139/147985480-a90f54b7-16b9-4655-b1f8-0e3aee51e0c1.png)

**Comment by hostar** [comment]
Try this https://github.com/hostar/python-inlay-putter/releases/tag/0.0.7

**Comment by Danjar27** [comment]
> Try this https://github.com/hostar/python-inlay-putter/releases/tag/0.0.7

Still got an error with 0.0.7 release. Any idea why could this be?

![image](https://user-images.githubusercontent.com/76726139/148103239-83a3b0f0-1549-4c62-bf99-7e2b9c2f55b0.png)

**Comment by hostar** [comment]
This one was trickier - try this: https://github.com/hostar/python-inlay-putter/releases/tag/0.0.7.1

**Comment by Danjar27** [comment]
It worked! Thanks, man
