### ISSUE TITLE
Error on Pycharm Pro 2022.3.1

### ISSUE THREAD

**Issue by teodor-t-tenev** [hostar/python-inlay-putter#7]
I receive this when trying to install the plugin
<img width="425" alt="image" src="https://user-images.githubusercontent.com/89847855/211589726-79336f35-746c-4c8b-a2d2-9bfe9531fec7.png">

**Comment by hostar** [comment]
Hello, it would not be hard to fix, this, but did you try this plugin instead? : https://github.com/WhiteMemory99/Intellij-Python-Inlay-Params

**Comment by teodor-t-tenev** [comment]
Thanks a lot that plugin worked!
